# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "WeatherPing" do

pod "Parse"
pod "ReactiveCocoa"
pod "UIImageEffects"

end

target "WeatherPingTests" do

end

